from .emotion_state import SYSTEM_PROMPT_TEMPLATE as EMOTION_STATE_PROMPT
from .action import SYSTEM_PROMPT_TEMPLATE as ACTION_PROMPT
from .animal import SYSTEM_PROMPT_TEMPLATE as ANIMAL_PROMPT
from .sports import SYSTEM_PROMPT_TEMPLATE as SPORTS_PROMPT
from .nature import SYSTEM_PROMPT_TEMPLATE as NATURE_PROMPT

PROMPT_TEMPLATES = {
    "감정/상태": EMOTION_STATE_PROMPT,
    "행동": ACTION_PROMPT,
    "동물": ANIMAL_PROMPT,
    "스포츠": SPORTS_PROMPT,
    "자연": NATURE_PROMPT,
}

DEFAULT_PROMPT_TEMPLATE = ANIMAL_PROMPT
